# # ---- Docker ----

# [container.image]
# repository="wso2inc" # Docker hub name
# name="hello" # container name
# tag="v0.1.0"

# [settings]
# buildImage=true # you can make this false if you don't want to build the image and you just need the Dockerfile

# # ---- Kubernetes ----

# [container.image]
# repository="wso2inc" # Ex - Docker hub repository name.
# name="hello-k8s" # Container name
# tag="v0.1.0"

# [cloud.deployment]
# min_memory="100Mi" # Minimum memory required for the container.
# max_memory="256Mi" # Maximum memory a single container can take.
# min_cpu="500m"  # Minimum CPU required for the container.
# max_cpu="500m" # Maximum CPU a single container can take.

# [cloud.deployment.autoscaling]
# min_replicas=2 # Minimum number of container instances ran at a given time
# max_replicas=5 # Maximum number of replicas of the container can scale up to
# cpu=60 # Average CPU utilization of pods

# [[cloud.config.files]] # Mounts the `Config.toml` file as a config map in Kubernetes.
# file="./Config.toml"
